# Generated by Django 3.1.6 on 2021-03-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
